runtime: nodejs20  # Updated to Node.js 20
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  STRIPE_SECRET_KEY: "sk_test_51Qyo4zGf0OHXso0nP3d4oidaARiWdkMK9T1U2IJeSqkiO3i83NsCKlyUMIMVNmLV2leDyrLMBs6rYUdEQBBPmm0N00QHvftVBL"
  STRIPE_WEBHOOK_SECRET: "whsec_jkAYutxnlnjxXyO4M2OsU0ZpnyLB1fJ4"